#
# Copyright (c) 2022 Amazon.com, Inc. or its affiliates.  All rights reserved.
#
# PROPRIETARY/CONFIDENTIAL.  USE IS SUBJECT TO LICENSE TERMS.
#
schema-version = 1

[package]
title = "Basic UI React Native Application"
version = "0.1.0"
id = "com.segment.keplersample83"

[components]
[[components.interactive]]
id = "com.segment.keplersample83.main"
runtime-module = "/com.amazon.kepler.runtime.react_native_kepler_4@IReactNativeKepler_0"
categories = ["com.amazon.category.main"]
launch-type = "singleton"
